import { Body, Controller, Get, Param, Post } from '@nestjs/common';

@Controller('api/users')
export class UsersController {
  @Post('update-password-email')
  updatePasswordEmail(@Body() payload: { email: string }): object {
    return {
      data: {
        message: `Se ha enviado un enlace para restablecer la contraseña a tu correo electrónico ${payload.email}.`,
        result: '1-661ee2ef-2ab2a3866e6a6505362b14df',
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Post('update-password/:token')
  updatePasswordWithToken(
    @Param('token') token: string,
    @Body() payload: { password: string; confirmPassword: string },
  ): object {
    return {
      data: {
        message: ' Contraseña restablecida con éxito con su correo:',
        result: null,
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Post('update-password')
  updatePassword(
    @Body() payload: { email: string; password: string; newPassword: string },
  ): object {
    return {
      data: {
        message: `Contraseña actualizada con éxito: ${payload}.`,
        result: [
          {
            id: 49,
            email: 'camilo.saavedra+0003@proactivess.cl',
            name: 'User',
            lastName: 'user',
            password:
              '$2a$10$G8HV4S0ec.cJlRoeLhkPzOtayYT5SkpR2XUzM2whsXpIRfzcHD3Mm',
            company: 'Test',
            company_id: 60,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2022-05-25T15:26:24.000Z',
            img: 'perfil:49-dbaabcdf-10a8-43a2-ad64-22832584dd16',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
        ],
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Get('getAll')
  getAll() {
    return {
      data: {
        message: 'Registros encontrados exitosamente',
        result: [
          {
            id: 7,
            email: 'camilo.saavedra@proactivess.cl',
            name: 'Test Editor',
            lastName: 'Saavedra',
            password:
              '$2a$10$KeIaswBCtNAhhhohdP6quu/d5Jrs63bdYPL9nUkZCdnlZoWnquH.m',
            company: 'test',
            company_id: 60,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-05-25T11:26:24.000Z',
            img: 'perfil:7-d82fdfb3-e3ef-44c0-b957-7efc6c29574a',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 10,
            email: 'frojas@neocomunicaciones.com',
            name: 'Francisco',
            lastName: null,
            password:
              '$2a$10$P4oFGSFDIbGnVDuKek/zgezdVunWnnWxfb4qghVKLaN8pAF1J/zVu',
            company: 'Test',
            company_id: 60,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-06-19T13:24:54.000Z',
            img: 'perfil:10-bfe96c80-6630-491b-833d-1b477416e5f1',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 11,
            email: 'ci.saavedras@gmail.cl',
            name: 'Test Admin',
            lastName: null,
            password:
              '$2a$10$.L8na2MxkHr4Atr3dktzVunf5yO0nEVa4ihNg5CiKiqk5E0Pw1cei',
            company: 'test',
            company_id: 60,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-06-27T14:26:34.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 12,
            email: 'guillermo.salas@proactivess.cl',
            name: 'Guillermo',
            lastName: null,
            password:
              '$2a$10$lwp3b3BKbFg9t/eXhmyI2.ad9T5BMY8RxifOcHiOvwTvDCtq1E79.',
            company: 'test',
            company_id: 60,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-06-28T13:28:05.000Z',
            img: 'perfil:12-c92e8893-7ea5-4ff8-925e-a5ad5d69452c',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 27,
            email: 'test@test.com',
            name: 'Test',
            lastName: 'Testing',
            password:
              '$2a$10$FDHZ6UNLmGxmy3uEg3ZiFuGukInTzaP5WrWsbUOwQ8FNCm5lkw7YC',
            company: 'Test ',
            company_id: 60,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-06T13:30:29.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 35,
            email: 'editor@editor.cl',
            name: 'Editor 2',
            lastName: 'Testing',
            password:
              '$2a$10$KhK3t9Mv4.3JSTNfejemBeYCkIQqslhWtyDFnqvFOiNY2p9vJdIWm',
            company: 'test 3',
            company_id: 67,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-06T20:23:09.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 36,
            email: 'editor3@editor.cl',
            name: 'Editor 3',
            lastName: 'testing 3',
            password:
              '$2a$10$/CvnRS.SntDSJOTsfLFzw.aziBcATG7ge2RYVlmOS4ni8NosMDT9W',
            company: 'test 3',
            company_id: 67,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-06T20:25:19.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 37,
            email: 'test4@test.com',
            name: 'Editor 4',
            lastName: 'Testion',
            password:
              '$2a$10$NuTU83FTFrA4Te.EYzbm7ebWi2DguBLcXygVnPEqXCXF2PU9VhDs.',
            company: 'test 3',
            company_id: 68,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-06T20:26:43.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 38,
            email: 'editor5@editor.cl',
            name: 'Editor 5',
            lastName: 'Editor',
            password:
              '$2a$10$BTZiQELtpSO35ZIcEwscB.cxR6Hg/XtEu4D7ZATFaLOiquCQf4iUW',
            company: 'Test ',
            company_id: 60,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-07T00:06:20.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 39,
            email: 'brenda@neocomunicaciones.com',
            name: 'Brenda',
            lastName: 'powier',
            password:
              '$2a$10$j82rRN8iuhiBKIHZCUdsaOXe2okRXfG/lN6wDxWAt0UaOh7vpmLny',
            company: 'Test ',
            company_id: 60,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-12T19:26:25.000Z',
            img: null,
            password_reset_token: '48781647-ea62-47f3-b91a-8525e6aec024',
            password_reset_token_expiration: '2023-11-09T15:55:36.000Z',
          },
          {
            id: 40,
            email: 'frojas@entornode.com',
            name: 'Francisco',
            lastName: 'Rojas',
            password:
              '$2a$10$vNUOiVAPrw99jW2zY3NZMuYItmEA7BvsGEN6s9BLm9Nwgz4Xq0Df6',
            company: 'Test ',
            company_id: 60,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-12T19:27:04.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 41,
            email: 'mdaniel@neocomunicaciones.com',
            name: 'Mayra',
            lastName: 'Daniel',
            password:
              '$2a$10$RGhxA5TQNzVBKI4kmQAGw.oJaDkC6WelXvcqMT.W9YO1mKhcZCUIK',
            company: 'Test ',
            company_id: 60,
            role: 'editor',
            publicaciones: 1,
            status: 'Activo',
            created_at: '2023-07-17T15:10:29.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 42,
            email: 'edith@neocomunicaciones.com',
            name: 'Edith',
            lastName: 'Suerez',
            password:
              '$2a$10$kfN4opNp4/1032arDuYdBuvqd1IG4f7Hj.23fcgNr.nD.Nm9eq7Mq',
            company: 'Test ',
            company_id: 60,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-17T15:11:03.000Z',
            img: null,
            password_reset_token: '2ccd4581-79d8-4768-9bc7-0ddd83ec9b81',
            password_reset_token_expiration: '2023-11-13T16:52:00.000Z',
          },
          {
            id: 43,
            email: 'ggarcia@neocomunicaciones.com',
            name: 'Gabriela',
            lastName: 'Garcia',
            password:
              '$2a$10$OQpB1T8yg23RX.P/CuvQLORUoFhJJQJWotsUem5O7i8NpgRz5yEba',
            company: 'Test ',
            company_id: 60,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-17T15:11:26.000Z',
            img: null,
            password_reset_token: 'd7d6ef9d-839d-4827-ad2a-c6499c162e93',
            password_reset_token_expiration: '2023-11-27T21:26:19.000Z',
          },
          {
            id: 44,
            email: 'fabiola@neocomunicaciones.com',
            name: 'Fabiola',
            lastName: 'Hidalgo',
            password:
              '$2a$10$/YEwZYBMLQ/UAXEsqr73ye7SgPs7AI9s1/y7/gTvDCzEUEEqW.fz.',
            company: 'Test ',
            company_id: 60,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-17T15:12:03.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 45,
            email: 'salvador@neocomunicaciones.com',
            name: 'Salvador',
            lastName: 'Sierra',
            password:
              '$2a$10$EaKf6RfgYGFKKDxOw4nmHOdHi1HXUhWfZWchAbQq.LlcGXC8aolOu',
            company: 'Test ',
            company_id: 60,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-17T15:12:50.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 47,
            email: 'camilo.saavedra+0001@proactivess.cl',
            name: 'Admin',
            lastName: 'admin',
            password:
              '$2a$10$.PxneUefizLs9GnUEgwkRezWLRzcDuG5e3lCG4COE3dpZqsGlvXJ6',
            company: 'Test',
            company_id: 60,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2021-07-18T16:28:09.000Z',
            img: 'perfil:47-7c644eb8-5141-4660-99b8-3246d5466395',
            password_reset_token: 'ee799277-1d7a-43a7-aee1-54207249ed62',
            password_reset_token_expiration: '2023-11-14T17:34:47.000Z',
          },
          {
            id: 48,
            email: 'camilo.saavedra+0002@proactivess.cl',
            name: 'Editor',
            lastName: 'editor',
            password:
              '$2a$10$IH7sk/XYGaY/CNA1a.lOK.kQh/PL6L63Opy9vamqxBer61x3lr4UC',
            company: 'Test',
            company_id: 60,
            role: 'editor',
            publicaciones: 12,
            status: 'Activo',
            created_at: '2023-01-18T16:31:54.000Z',
            img: 'perfil:48-8a3ae301-2d8b-44d2-8230-c723554f9c46',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 49,
            email: 'camilo.saavedra+0003@proactivess.cl',
            name: 'User',
            lastName: 'user',
            password:
              '$2a$10$kLV/Bvp88oTk2nHNEl16aOzYemzx2noATlNOZ9jKJU8uVgd9WilSW',
            company: 'Test',
            company_id: 60,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2022-05-25T11:26:24.000Z',
            img: 'perfil:49-dbaabcdf-10a8-43a2-ad64-22832584dd16',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 61,
            email: 'camilo.saavedra+0005@proactivess.cl',
            name: 'Test 5',
            lastName: 'Test 5',
            password:
              '$2a$10$b61i/2sylkTxToYT0yyHFeBkFQCsWfE.1CTrVHdbkm9L97zV6KinS',
            company: 'Test',
            company_id: 60,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-25T22:31:35.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 62,
            email: 'camilo.saavedra+0006@proactivess.cl',
            name: 'Blacky ',
            lastName: 'Salas',
            password:
              '$2a$10$TDt1RyPN2NCfNqC2B5vjiu9mQdJ.HMwGbaV59C6oTwel7aA71DCsO',
            company: 'Proactivess SPA',
            company_id: 76,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-26T15:55:00.000Z',
            img: 'perfil:62-64675a7d-b074-4fc6-b561-f4af9f265a8d',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 63,
            email: 'camilo.saavedra+0007@proactivess.cl',
            name: 'Thor',
            lastName: 'Saavedra',
            password:
              '$2a$10$Trn9ve05BqUk.5TJt8PCTu14Zg1khAreNyezQhSEhrpGIYoFXFARS',
            company: 'Proactivess SPA',
            company_id: 76,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-26T15:56:08.000Z',
            img: 'perfil:63-d229a82f-9e2a-48b3-b3b5-a7fda5f90b35',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 64,
            email: 'frojas@knowsy.ai',
            name: 'FRANCISCO',
            lastName: 'ROJAS BARROS',
            password:
              '$2a$10$9lYVioHAWvfYi.qUEeXK/uXVxCnEAN7EY93.PebHhAOAnRyRBrrrW',
            company: 'Knowsy',
            company_id: 77,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-26T20:28:22.000Z',
            img: 'perfil:64-f2f7a02d-ff51-44c9-a5a2-a82e90509718',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 66,
            email: 'guillermo.salas+0002@proactivess.cl',
            name: 'Guillermo ',
            lastName: 'Salas Editor',
            password:
              '$2a$10$A6cq2SNp3G6KguY0iZLMcu3OCTqk/rCrYkE.cx.WlWLdNcdKhcPta',
            company: 'Proactivess SPA',
            company_id: 76,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-07-28T20:41:31.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 67,
            email: 'guadalupe@cleanranks.com',
            name: 'Guadalupe',
            lastName: 'Campos',
            password:
              '$2a$10$UF8vC9Q2e6PuG/VHt/aE2ORn7tIaO2YpR/OFIIzBCaNQMQ5Ye5OPS',
            company: 'Clean Ranks',
            company_id: 79,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-01T01:17:32.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 68,
            email: 'marian@neocomunicaciones.com',
            name: 'MARIA ANTONIETA',
            lastName: 'CAMARENA AMAYA',
            password:
              '$2a$10$GeCkT.d8sFvy7JdRCgbPHueb4rATnwUnvWk9QCO5IINDOC2T7cvM.',
            company: 'Proactivess SPA',
            company_id: 76,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-01T01:33:41.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 69,
            email: 'camilo.saavedra+0010@proactivess.cl',
            name: 'Test 10',
            lastName: 'Test 10',
            password:
              '$2a$10$t/kEVfiLArLQhh6TjTgq1uXYrU5OhTSZqWicL2Ts5yn7jbSZQIDZy',
            company: 'Proactivess SPA',
            company_id: 76,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-04T17:22:26.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 70,
            email: 'guillermo.salas+0003@proactivess.cl',
            name: 'Buenamonte',
            lastName: 'Carloncho',
            password:
              '$2a$10$mCejUcy6kXs690GbrEPcS.WxAxzCE1IlvGulGlGisoSBvcOR29NRW',
            company: 'Testing Posting',
            company_id: 80,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-09T23:43:36.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 84,
            email: 'guillermo.salas+2023@proactivess.cl',
            name: 'Editor',
            lastName: 'Neo Test',
            password:
              '$2a$10$f4Q78i2SomJ0nJlvRDbUuerat7ky9/Ld1QLzQ/iqZ4.UJr4v7p83S',
            company: null,
            company_id: null,
            role: 'editor',
            publicaciones: 3,
            status: 'Activo',
            created_at: '2023-08-28T17:05:01.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 89,
            email: 'camilo.saavedra+0009@proactivess.cl',
            name: 'Nuevo Test',
            lastName: 'Nuevo Test',
            password:
              '$2a$10$rpLQpwOVt7H1fCbBJguDHuvbwYCxCcyxCjLv.ak1fx7csElofTvZu',
            company: 'Nueva empresa Test',
            company_id: 86,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-30T13:55:23.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 90,
            email: 'camilo.saavedra+0011@proactivess.cl',
            name: 'Nuevo Test ',
            lastName: 'Nuevo Test 2',
            password:
              '$2a$10$lryk/mFry7WrOKjtIcjjfOwMEISzMpYgEByujRCnhFyJssuqJU5vu',
            company: 'Nueva empresa Test 2',
            company_id: 87,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-30T14:04:33.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 91,
            email: 'camilo.saavedra+0015@proactivess.cl',
            name: 'Test 10',
            lastName: 'Test 10',
            password:
              '$2a$10$XJ70wxZLQE/GefcZbIHzpuxEppCMd4EaRadbGv8VUR/yPuCou4fFW',
            company: null,
            company_id: null,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-30T16:35:51.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 92,
            email: 'camilo.saavedra+0016@proactivess.cl',
            name: 'John',
            lastName: 'Doe',
            password:
              '$2a$10$uTEQf.E0/yq8iILMLMIUhe74cEFijngpeFjrYaIX27k.qpBkXE6VS',
            company: 'ABC Tours',
            company_id: 88,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-08-30T17:33:34.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 94,
            email: 'camilo.saavedra+0100@proactivess.cl',
            name: 'bugTest',
            lastName: 'bugTest',
            password:
              '$2a$10$gplZZG8KKP48q9LiuzaYq.h9ChZwRLmPfaVOyDfx00QjW/obft7t.',
            company: 'Diálogo Corporativo',
            company_id: 90,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-09-15T15:52:17.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 95,
            email: 'camilo.saavedra+099@proactivess.cl',
            name: 'Test Bug ',
            lastName: 'Test Bug ',
            password:
              '$2a$10$R7Xw575sUjtBgG7ZH0C1sOQgNbEOtMoQz6SNZRKzbFlhtoirGODUO',
            company: 'Test bug',
            company_id: 91,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-09-15T19:20:57.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 96,
            email: 'camilo.saavedra+0018@proactivess.cl',
            name: 'Camilo',
            lastName: 'Saavedras',
            password:
              '$2a$10$wZQlC/O4pN9rLZFtMXbSkewyuSJtPU0iEfe8lcOvztvpVsrm44Sni',
            company: 'XYZ Compañía',
            company_id: 92,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-10-11T15:23:17.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 97,
            email: 'camilo.saavedra+0022@proactivess.cl',
            name: 'Ana',
            lastName: 'García',
            password:
              '$2a$10$fvyyvhgp57a1d07HelQZAeHfGyLjxhOY1ynEJY8BcZBbhpn2ajoR6',
            company: 'Innovatech Solutions',
            company_id: 93,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-10-11T17:24:43.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 98,
            email: 'camilo.saavedra+0032@proactivess.cl',
            name: 'Camilo10',
            lastName: 'Saavedra10',
            password:
              '$2a$10$ooGh/Fw4l7V2zZN92BSHnOnAE6LjZHEpItfq2rGRKUhQnVaotZFbK',
            company: 'Test10',
            company_id: 94,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-10-12T11:58:40.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 99,
            email: 'camilo.saavedra+0200@proactivess.cl',
            name: 'Camilo ',
            lastName: 'Saavedra',
            password:
              '$2a$10$sNalVV5dBYm6NsFpR/LMSe48zri4DzOfx6Zt0hDt1Ij0VrNEtw9ym',
            company: 'ABC Compañía',
            company_id: 95,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-10-31T20:58:44.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 100,
            email: 'javier.rosales@proactivess.cl',
            name: 'Javier',
            lastName: 'Rosales',
            password:
              '$2a$10$/StogzTZN0N/XLQjh0XXUeUByEmZyh9l4VnijWNsVYILXdvSx0a6a',
            company: 'Empresa Javier ',
            company_id: 96,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-02T13:18:05.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 101,
            email: 'camilo.saavedra+0500@proactivess.cl',
            name: 'Camilo',
            lastName: 'Saavedra',
            password:
              '$2a$10$sWmR8NLsdlpEGCIzzc/6i.zmD.DvsXJdRO2EdapgNLyFiOFPbuGuG',
            company: 'Camilo SPA',
            company_id: 97,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-02T13:25:45.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 102,
            email: 'camilo.saavedra+0501@proactivess.cl',
            name: 'Camilo ',
            lastName: 'Saavedra ',
            password:
              '$2a$10$33r1mUafChYYEC1IH.F59umOPUNECVsZTdEVl0zYZZ3G5XzLatawu',
            company: 'Test 500',
            company_id: 98,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-02T13:28:43.000Z',
            img: null,
            password_reset_token: '83ab0f2b-c2c5-4460-a12a-8d4026b8fa1a',
            password_reset_token_expiration: '2023-11-09T10:26:00.000Z',
          },
          {
            id: 103,
            email: 'camilo.saavedra+0503@proactivess.cl',
            name: 'Camilo',
            lastName: 'Saavedra',
            password:
              '$2a$10$CQ7y33KDNdgI5eWyzODwX.LxsvZ.ryeiwSL7BS1uA0omFoQvV0/Yy',
            company: 'Testing 501',
            company_id: 99,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-02T17:55:14.000Z',
            img: null,
            password_reset_token: 'a14a14ff-6621-4419-abda-a95f8bfe1808',
            password_reset_token_expiration: '2023-11-09T09:38:43.000Z',
          },
          {
            id: 104,
            email: 'guillermo.salas+0005@proactivess.cl',
            name: 'Guillermo',
            lastName: 'Salas',
            password:
              '$2a$10$zdHKaWY82pdh3QkwMnre8u7CwxUU.3vsm23ZgBqsDecPvFoiL76Na',
            company: 'Proactivess',
            company_id: 100,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-03T19:02:36.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 105,
            email: 'sathia@devmexico.com',
            name: 'Sathia',
            lastName: 'Toro',
            password:
              '$2a$10$zagsTeWfgpvIHVVRFAv6dOYM5loFk6YADvdl5.ehbMVj04UTgaZ.i',
            company: 'Ganar Ganar',
            company_id: 101,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-06T19:03:29.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 106,
            email: 'camilo.saavedra+0044@proactivess.cl',
            name: 'Camilo',
            lastName: 'Saavedra',
            password:
              '$2a$10$16qvdWutrP7pv.ZToPRj2e2K4HTs7R/o/q02iO3IIR7c3EFPMc5UK',
            company: 'DFG Company test',
            company_id: 102,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-07T20:55:27.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 107,
            email: 'francisco.revistaneo+01@gmail.com',
            name: 'FRANCISCO JOSE',
            lastName: 'ROJAS BARROS',
            password:
              '$2a$10$ML9InLxQ42pANITHcc9AE.wFv8z1EsuaPEjQtZRqXdDE3xveGLT16',
            company: 'Entorno dearketing y tecnología SA de cv Camarena',
            company_id: 103,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-09T01:12:40.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 108,
            email: 'francisco.revistaneo+001@gmail.com',
            name: 'FRANCISCO',
            lastName: 'BARROS',
            password:
              '$2a$10$JYVwcxxVLJV5EscrRe80teJzrdzGk/kODshObsaH3xm7fytnjSD3e',
            company: 'Entorno dearketing y tecnología SA de cv Camarena',
            company_id: 104,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-09T01:18:42.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 109,
            email: 'jose@neocomunicaciones.com',
            name: 'JOSE',
            lastName: 'BARROS',
            password:
              '$2a$10$eSoLTPn4jaKBUQCPOZQT1uOxZ8sm82ahHdB1DXuO/VaTxd4vvKv1e',
            company: 'Tway',
            company_id: 105,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-09T14:24:11.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 123,
            email: 'camilo.saavedra+0004@proactivess.cl',
            name: 'John',
            lastName: 'Doe',
            password:
              '$2a$10$W3bimqa36xSXkDnWbP5mEeFUWpmlnFEj5oK57X1pajppzb6Kopi0e',
            company: 'Tech Innovators Inc.',
            company_id: 119,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-09T19:13:53.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 124,
            email: 'camilo.saavedra+0012@proactivess.cl',
            name: 'John',
            lastName: 'Doe',
            password:
              '$2a$10$Nrxa3K0ZZc1j483A4fBReeBHiRDzKnj.jvDcrRtFgvmrQKxBdL2bG',
            company: 'Tech Innovators Inc.',
            company_id: 120,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-10T21:21:26.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 125,
            email: 'alex.global@globalmarketingsolutions.com',
            name: 'Alex',
            lastName: 'Global',
            password:
              '$2a$10$rfFOHvCOo2G8cdzLd6Bya.HGKvjNVk9yUr9rCyxPfJsJ5R6PMqQm2',
            company: 'Global Marketing Solutions',
            company_id: 121,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-13T15:22:03.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 126,
            email: 'camilo.saavedra+0055@proactivess.cl',
            name: 'Emma',
            lastName: 'Designer',
            password:
              '$2a$10$B0BOGj4csN7W.00059bfg.3ReB28NUhBTQQUlwluk3sy9Iuc0y1E6',
            company: 'Creative Concepts Co.',
            company_id: 122,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-13T15:23:25.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 127,
            email: 'camilo.saavedra+0013@proactivess.cl',
            name: 'John',
            lastName: 'Smith',
            password:
              '$2a$10$.AIOmIAkMhN8W2thGr8luuasuvPWG.1TNE6PXUHro.mKa6Fa6rfqC',
            company: 'Digital Dynamics Inc',
            company_id: 123,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-13T15:31:40.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 128,
            email: 'camilo.saavedra+0014@proactivess.cl',
            name: 'John',
            lastName: 'Jobs',
            password:
              '$2a$10$AMvLN.Y8Nhg7LyRmSFWPQObx56JsFeT8Q7Exc8WLsp2MWM27cu40G',
            company: null,
            company_id: null,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-13T15:33:34.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 129,
            email: 'camilo.saavedra+0017@proactivess.cl',
            name: 'Susan',
            lastName: 'Smart',
            password:
              '$2a$10$/gVwu/HUnib4Ae2zVxAfb.6eexQWDh5JqFw27LhTsVVg3lNGs4w0m',
            company: 'Smart Solutions Tech',
            company_id: 124,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-13T16:33:31.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 130,
            email: 'camilo.saavedra+0019@proactivess.cl',
            name: 'David',
            lastName: 'Innovator',
            password:
              '$2a$10$l52ouoqAvjvwTWXl.y9vauqjsQutHkxKbbG0tnXzr.vVmJjFvsHXu',
            company: 'Infinite Innovations Corp',
            company_id: 125,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-13T18:03:37.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 131,
            email: 'camilo.saavedra+0020@proactivess.cl',
            name: 'Sarah',
            lastName: 'Visionary',
            password:
              '$2a$10$O5Bpw29EROtlT4AmvhvJh.bfx93n8//MpCMwB/jvp2cMOkPFNndiy',
            company: 'Visionary Ventures Inc',
            company_id: 126,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-11-13T18:05:44.000Z',
            img: null,
            password_reset_token: 'cacc36a4-32d2-4ee4-b53a-525f36018fad',
            password_reset_token_expiration: '2023-11-13T19:11:00.000Z',
          },
          {
            id: 132,
            email: 'camilo.saavedra+0300@proactivess.cl',
            name: 'Camilo',
            lastName: 'Saavedra',
            password:
              '$2a$10$t7/5QItVpzByH.d.3Erlmez/kJTCK3xHWOQ0PLe649GhvNIu/Ky7e',
            company: null,
            company_id: null,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2023-12-05T13:04:21.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 133,
            email: 'guillermo.salas+editor@proactivess.cl',
            name: 'Guillermo',
            lastName: 'Salas',
            password:
              '$2a$10$c1HUlWzzV/FVUtMr6TCGaOvbIHS1ox9gsolGSP1ojUdjjfuLW0KTa',
            company: null,
            company_id: null,
            role: 'editor',
            publicaciones: 2,
            status: 'Activo',
            created_at: '2024-02-29T10:38:29.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 134,
            email: 'guillermo.salas+cliente@proactivess.cl',
            name: 'Guillermo',
            lastName: 'Cliente',
            password:
              '$2a$10$VFAYbofvmAhGfGtsEMg45O1eZ7rmtZxVhn0VSS5vvowTEM1P.fRse',
            company: 'Proactivess Test',
            company_id: 127,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-02-29T10:52:42.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 135,
            email: 'camilo.saavedra+0600@proactivess.cl',
            name: 'Camilo',
            lastName: 'Saavedra',
            password:
              '$2a$10$fzKoyzBA8mYnBYBeSvFwc.6YXXVOOXWUZn9YJf7aZsIXOAMrUxsrm',
            company: 'Apple ',
            company_id: 128,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-03-01T12:39:29.000Z',
            img: 'perfil:135-92dd4e85-4688-4f01-8098-8833254cfa66',
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 136,
            email: 'marcelo.emmott+admin@proactivess.cl',
            name: 'marcelo',
            lastName: 'administrador',
            password:
              '$2a$10$DD9EWyWOWtuk0CXXq9ZOJurX935PeWY/UNMBi7cw.DBMXZBDHMeJm',
            company: null,
            company_id: null,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-03-01T18:26:07.000Z',
            img: 'perfil:136-d51802cc-93dd-4e68-85f2-3cbdbee50f83',
            password_reset_token: 'bd87c1a8-6d96-4302-aaf2-617270e02e74',
            password_reset_token_expiration: '2024-03-05T13:35:00.000Z',
          },
          {
            id: 137,
            email: 'alejoemmott@gmail.com',
            name: 'memmott30',
            lastName: 'sanchez',
            password:
              '$2a$10$7U0klGdquBLeM4mA6SdfB.KvoUyiQ6x3I9HLRWomPvKpGYfASrocC',
            company: 'proactivess',
            company_id: 129,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-04-16T18:42:03.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 138,
            email: 'camilo.saavedra+0018@proactivess.cl',
            name: 'Camilo',
            lastName: 'Saavedras',
            password:
              '$2a$10$B5xOPjhXV2GPIl7zhVDSp.zbsP5UPkeo1fg9rEesw3LdV5jh230Mq',
            company: 'proactivess',
            company_id: 130,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-04-16T18:58:02.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 139,
            email: 'alejoemmot@gmail.com',
            name: 'marcelo',
            lastName: 'emmott',
            password:
              '$2a$10$tVNHTEWwLikVqmB.seHkUO8wXZ2pTabtnCZHKeTksH8VhmJUkYqtG',
            company: 'Test 45',
            company_id: 60,
            role: null,
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-04-16T15:19:03.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 140,
            email: 'alejoemmot@gmadil.com',
            name: 'marcelo',
            lastName: 'emmott',
            password:
              '$2a$10$lo2NOPDw4xPvrWIPUnC6G.ziBft.YL7eqMHPpRZt6dzJcojvjLNo.',
            company: null,
            company_id: null,
            role: 'admin',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-04-16T19:23:47.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 141,
            email: 'camilo.saavedra+5000@proactivess.cl',
            name: 'Marcelo ',
            lastName: 'Emotte',
            password:
              '$2a$10$EKBxflgOZ2G6bCHC5wOE8.9xnzOKMfNJfFvO6vf9G.CixxD45LQSy',
            company: null,
            company_id: null,
            role: 'editor',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-04-16T20:27:08.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 142,
            email: 'alejoemmotct@gmail.com',
            name: 'memmott30',
            lastName: 'sanchez',
            password:
              '$2a$10$tmxZg5rAW2u7sqHwfaKOb.hSjYf9Eej6pF7OkYykYYT.XhXyApCM6',
            company: 'proactivess',
            company_id: 131,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-04-17T12:14:10.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
          {
            id: 143,
            email: 'alejoemmotct@gmgail.com',
            name: 'memmott30',
            lastName: 'sanchez',
            password:
              '$2a$10$QzAFx9om7j1qIPsXQmls4uwDXLRpZoPMOu3NmJsYeUwaqFAHGD9VW',
            company: 'proactivess',
            company_id: 132,
            role: 'user',
            publicaciones: 0,
            status: 'Activo',
            created_at: '2024-04-17T19:03:57.000Z',
            img: null,
            password_reset_token: null,
            password_reset_token_expiration: null,
          },
        ],
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Get('getUser/:id')
  getUserById(@Param('id') id: number): object {
    return {
      data: {
        message: `Datos obtenidos correctamente con este ${id}`,
        result: {
          id: id,
          email: 'camilo.saavedra+0001@proactivess.cl',
          name: 'Admin',
          lastName: 'admin',
          password:
            '$2a$10$.PxneUefizLs9GnUEgwkRezWLRzcDuG5e3lCG4COE3dpZqsGlvXJ6',
          company: 'Test',
          company_id: 60,
          role: 'admin',
          publicaciones: 0,
          status: 'Activo',
          created_at: '2021-07-18T20:28:09.000Z',
          img: 'perfil:47-7c644eb8-5141-4660-99b8-3246d5466395',
          password_reset_token: 'ee799277-1d7a-43a7-aee1-54207249ed62',
          password_reset_token_expiration: '2023-11-14T20:34:47.000Z',
        },
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Get('get-image/:id')
  getImageUserById(@Param('id') id: number): object {
    return {
      data: {
        message: `Se obtuvo el source de imagen correctamente con este ${id}`,
        result:
          'https://agency-perfil-images.s3.us-east-1.amazonaws.com/perfil%3A47-7c644eb8-5141-4660-99b8-3246d5466395?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAQGNFOHYDRCHRAU6H%2F20240416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240416T202408Z&X-Amz-Expires=60&X-Amz-Signature=e17f2a62d4c4b59cf22a098bf250b842f8af73e2e2af405b661570bb2e4b4231&X-Amz-SignedHeaders=host&x-id=GetObject',
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Post('update/admin/:id')
  updateAdminById(
    @Param('id') id: number,
    @Body()
    payload: {
      email: string;
      name: string;
      lastName: string;
    },
  ): object {
    return {
      data: {
        message: `Información actualizada correctament con este id: ${id}`,
        result: [
          {
            fieldCount: 0,
            affectedRows: 1,
            insertId: 0,
            info: 'Rows matched: 1  Changed: 1  Warnings: 0',
            serverStatus: 2,
            warningStatus: 0,
            changedRows: 1,
          },
          null,
        ],
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Post('add/admin')
  addUserAdmin(
    @Body()
    payload: {
      name: string;
      lastName: string;
      email: string;
      role: string;
    },
  ): object {
    return {
      data: {
        message: `Información actualizada correctamente!`,
        result: {
          fieldCount: 0,
          affectedRows: 1,
          insertId: 141,
          info: '',
          serverStatus: 2,
          warningStatus: 0,
        },
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Post('create')
  createPost(
    @Body()
    payload: {
      image: string; // binary
      imageName: string;
      post_id: string;
      title: string;
      subtitle: string;
      category: string;
      content: string;
      user_id: number;
      tags: string; // array
      state: string;
      company_id: number;
    },
  ): object {
    return {
      data: {
        result: {
          fieldCount: 0,
          affectedRows: 1,
          insertId: 296,
          info: '',
          serverStatus: 2,
          warningStatus: 0,
        },
        message: 'Post creado correctamente',
      },
      status: 'Ok',
      code: 200,
      error: null,
    };
  }

  @Post('upload-image')
  uploadImage(){
    return {
      data:{
        message: 'Imagen subida correctamente',
        result: {
          fieldCount: 0,
          affectedRows: 1,
          insertId: 0,
          info: '',
          serverStatus: 2,
          warningStatus: 0,
        }
      }
    }
  }
}
